In [1]:
import tensorflow as tf

In [9]:
two_d_tensor = tf.constant(
    [
        [1,2,3.6,4],
        [6,4.4,5.5,3]
    ], 
    dtype=tf.float32
)

cast_two_d_tensor = tf.cast(two_d_tensor, dtype=tf.int16)
print(two_d_tensor)
print(cast_two_d_tensor)

tf.Tensor(
[[1.  2.  3.6 4. ]
 [6.  4.4 5.5 3. ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1 2 3 4]
 [6 4 5 3]], shape=(2, 4), dtype=int16)


In [5]:
three_d_tensor = tf.constant(
    [
        [
            [1,2,3],
            [9,3,7]
        ],
        [
            [1,2,9],
            [0,7,7]
        ]
    ]
)
print(three_d_tensor)
print(three_d_tensor.shape)
print(three_d_tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [9 3 7]]

 [[1 2 9]
  [0 7 7]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
3


In [6]:
four_d_tensor = tf.constant(
    [
        [
            [
                [1,2,3],
                [9,3,7]
            ],
            [
                [1,2,9],
                [0,7,7]
            ],
            [
                [8,2,3],
                [-9,3,7]
            ],
            [
                [5,8,9],
                [9,-8,7]
            ]
        ]
    ]
)
print(four_d_tensor)

tf.Tensor(
[[[[ 1  2  3]
   [ 9  3  7]]

  [[ 1  2  9]
   [ 0  7  7]]

  [[ 8  2  3]
   [-9  3  7]]

  [[ 5  8  9]
   [ 9 -8  7]]]], shape=(1, 4, 2, 3), dtype=int32)


In [10]:
import numpy as np

In [11]:
num_array = np.array([2, -5, 8])
print(num_array)

[ 2 -5  8]


In [12]:
converted_to_tensor = tf.convert_to_tensor(num_array)
print(converted_to_tensor)

tf.Tensor([ 2 -5  8], shape=(3,), dtype=int64)


In [16]:
eye_tensor = tf.eye(num_rows=3, num_columns=4)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]], shape=(3, 4), dtype=float32)


In [18]:
eye_tensor_four = tf.eye(num_rows=3, num_columns=4, batch_shape=[2,2])
eye_tensor_three = tf.eye(num_rows=3, num_columns=4, batch_shape=[2,])
print(eye_tensor_four)
print(eye_tensor_three)

tf.Tensor(
[[[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]]], shape=(2, 2, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape=(2, 3, 4), dtype=float32)


In [19]:
fill_tensor = tf.fill(dims=[2,3], value=4)
print(fill_tensor)

tf.Tensor(
[[4 4 4]
 [4 4 4]], shape=(2, 3), dtype=int32)


In [20]:
fill_tensor_three = tf.fill(dims=[2,2,3], value=-8)
print(fill_tensor_three)

tf.Tensor(
[[[-8 -8 -8]
  [-8 -8 -8]]

 [[-8 -8 -8]
  [-8 -8 -8]]], shape=(2, 2, 3), dtype=int32)


In [21]:
one_like_tensor = tf.ones_like(input=three_d_tensor)
print(one_like_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(2, 2, 3), dtype=int32)


In [22]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.shape(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3], dtype=int32)>

In [24]:
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.shape(t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [25]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [28]:
t = tf.constant(
    [
        [
            [1, 1, 1], [2, 2, 2]
        ],
        [
            [3, 3, 3], [4, 4, 4]
        ],
        [
            [5, 5, 5], [6, 6, 6]
        ]
    ])
tf.slice(t, [1, 0, 0], [1, 1, 3])  # [[[3, 3, 3]]]
tf.slice(t, [1, 0, 0], [1, 2, 3])  # [[[3, 3, 3],
                                   #   [4, 4, 4]]]
tf.slice(t, [1, 0, 0], [2, 1, 3])  # [[[3, 3, 3]],
                                   #  [[5, 5, 5]]]

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[3, 3, 3]],

       [[5, 5, 5]]], dtype=int32)>

In [31]:
random_normal_tensor = tf.random.normal(
    [3,2],
    mean=50,
    stddev=10.0
)
print(random_normal_tensor)

tf.Tensor(
[[42.99212  39.830017]
 [40.0785   38.94884 ]
 [47.74065  49.51425 ]], shape=(3, 2), dtype=float32)


In [32]:
random_uniform_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=20
)
print(random_uniform_tensor)

tf.Tensor([ 7.2950935 19.130877   4.4281697  8.248029  16.58386  ], shape=(5,), dtype=float32)


In [33]:
random_uniform_tensor = tf.random.uniform(
    [5,4],
    minval=-20,
    maxval=20
)
print(random_uniform_tensor)

tf.Tensor(
[[ 16.336384    5.2735615  -8.270335  -12.3969555]
 [ 10.375191    9.092659    1.5568638  -9.204917 ]
 [ -1.3422546   1.1723671  -2.4156227 -12.623072 ]
 [ 10.633764  -14.360361   19.326149  -11.243768 ]
 [ -3.7603989  -3.8772106   5.256033   19.497982 ]], shape=(5, 4), dtype=float32)


In [36]:
tf.random.set_seed(1234)
print(tf.random.uniform([4,3], seed=10))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([2,5], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=10))  # generates 'A2'

tf.Tensor(
[[0.85591054 0.32390785 0.6447526 ]
 [0.8316823  0.16297233 0.14103293]
 [0.2647568  0.2954973  0.6597587 ]
 [0.7494894  0.32736623 0.9407855 ]], shape=(4, 3), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor(
[[0.1689806  0.9725481  0.90036285 0.16582811 0.1454581 ]
 [0.48029935 0.02495587 0.99239147 0.02835405 0.10649502]], shape=(2, 5), dtype=float32)
tf.Tensor([0.85591054], shape=(1,), dtype=float32)


In [43]:
tensor_indexed = tf.constant(
    [1, 2, 5, -19, -8, 6]
)
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[:4]) #start from 0 index
print(tensor_indexed[2:]) #start from index 2 to end index
print(tensor_indexed[2:-1]) #start from index 2 and leave 1 index from end
print(tensor_indexed[1:5])
print(tensor_indexed[0:6:2])

tf.Tensor([  1   2   5 -19  -8   6], shape=(6,), dtype=int32)
tf.Tensor([  1   2   5 -19], shape=(4,), dtype=int32)
tf.Tensor([  1   2   5 -19], shape=(4,), dtype=int32)
tf.Tensor([  5 -19  -8   6], shape=(4,), dtype=int32)
tf.Tensor([  5 -19  -8], shape=(3,), dtype=int32)
tf.Tensor([  2   5 -19  -8], shape=(4,), dtype=int32)
tf.Tensor([ 1  5 -8], shape=(3,), dtype=int32)


In [54]:
tensor_indexed_two_d = tf.constant(
    [
        [1,2,3,5],
        [5,3,2,33],
        [-5,8,9,0],
        [6,-4,-7,-11],
        [5,9,2,7]
    ]
)
print(tensor_indexed_two_d[0:3, 0:2]) #first 2 column from first 3 rows
print(tensor_indexed_two_d[1:3, 1:3])
print(tensor_indexed_two_d[0:3, :]) #first 3 rows and all the columns
print(tensor_indexed_two_d[3, :]) #fourth row and all columns
print(tensor_indexed_two_d[:, 0]) #first column from all rows
print(tensor_indexed_two_d[..., 0]) #same as above
print(tensor_indexed_two_d[:, 1])

tf.Tensor(
[[ 1  2]
 [ 5  3]
 [-5  8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 2]
 [8 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  2  3  5]
 [ 5  3  2 33]
 [-5  8  9  0]], shape=(3, 4), dtype=int32)
tf.Tensor([  6  -4  -7 -11], shape=(4,), dtype=int32)
tf.Tensor([ 1  5 -5  6  5], shape=(5,), dtype=int32)
tf.Tensor([ 1  5 -5  6  5], shape=(5,), dtype=int32)
tf.Tensor([ 2  3  8 -4  9], shape=(5,), dtype=int32)


In [58]:
tensor_indexed_three_d = tf.constant(
    [
        [
            [1,2,3,5],
            [5,3,2,33],
            [-5,8,9,0],
            [6,-4,-7,-11],
            [5,9,2,7]
        ],
        [
            [3,5,3,5],
            [4,3,-7,33],
            [5,5,9,0],
            [6,4,-7,-11],
            [7,-9,-2,7]
        ],
        [
            [-1,2,3,5],
            [-5,9,2,33],
            [-5,90,96,70],
            [-6,4,-71,-11],
            [-5,99,12,27]
        ],
        [
            [12,-2,-3,54],
            [53,34,2,33],
            [-56,8,92,0],
            [61,-44,-7,-11],
            [53,49,21,87]
        ]
    ]
)
print(tensor_indexed_three_d[0:2, 1:3, :])
print(tensor_indexed_three_d[2, :, :]) #all values in 2nd index
print(tensor_indexed_three_d[:, :, -2]) 

tf.Tensor(
[[[ 5  3  2 33]
  [-5  8  9  0]]

 [[ 4  3 -7 33]
  [ 5  5  9  0]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[ -1   2   3   5]
 [ -5   9   2  33]
 [ -5  90  96  70]
 [ -6   4 -71 -11]
 [ -5  99  12  27]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[  3   2   9  -7   2]
 [  3  -7   9  -7  -2]
 [  3   2  96 -71  12]
 [ -3   2  92  -7  21]], shape=(4, 5), dtype=int32)
