In [1]:
import tensorflow as tf

In [9]:
two_d_tensor = tf.constant(
    [
        [1,2,3.6,4],
        [6,4.4,5.5,3]
    ], 
    dtype=tf.float32
)

cast_two_d_tensor = tf.cast(two_d_tensor, dtype=tf.int16)
print(two_d_tensor)
print(cast_two_d_tensor)

tf.Tensor(
[[1.  2.  3.6 4. ]
 [6.  4.4 5.5 3. ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1 2 3 4]
 [6 4 5 3]], shape=(2, 4), dtype=int16)


In [5]:
three_d_tensor = tf.constant(
    [
        [
            [1,2,3],
            [9,3,7]
        ],
        [
            [1,2,9],
            [0,7,7]
        ]
    ]
)
print(three_d_tensor)
print(three_d_tensor.shape)
print(three_d_tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [9 3 7]]

 [[1 2 9]
  [0 7 7]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
3


In [6]:
four_d_tensor = tf.constant(
    [
        [
            [
                [1,2,3],
                [9,3,7]
            ],
            [
                [1,2,9],
                [0,7,7]
            ],
            [
                [8,2,3],
                [-9,3,7]
            ],
            [
                [5,8,9],
                [9,-8,7]
            ]
        ]
    ]
)
print(four_d_tensor)

tf.Tensor(
[[[[ 1  2  3]
   [ 9  3  7]]

  [[ 1  2  9]
   [ 0  7  7]]

  [[ 8  2  3]
   [-9  3  7]]

  [[ 5  8  9]
   [ 9 -8  7]]]], shape=(1, 4, 2, 3), dtype=int32)


In [10]:
import numpy as np

In [11]:
num_array = np.array([2, -5, 8])
print(num_array)

[ 2 -5  8]


In [12]:
converted_to_tensor = tf.convert_to_tensor(num_array)
print(converted_to_tensor)

tf.Tensor([ 2 -5  8], shape=(3,), dtype=int64)


In [16]:
eye_tensor = tf.eye(num_rows=3, num_columns=4)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]], shape=(3, 4), dtype=float32)


In [18]:
eye_tensor_four = tf.eye(num_rows=3, num_columns=4, batch_shape=[2,2])
eye_tensor_three = tf.eye(num_rows=3, num_columns=4, batch_shape=[2,])
print(eye_tensor_four)
print(eye_tensor_three)

tf.Tensor(
[[[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]]]], shape=(2, 2, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape=(2, 3, 4), dtype=float32)
